### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by slick2** [irmec/irmec-website#6]
The contact page does not email to support rep upon submission.  Modify the contact controller located at application/controllers/pub.php look for the contact method.

**Comment by benjaminfaustino** [comment]
@slick2 Carey what exactly will I do to this contact page about emailing?

**Comment by slick2** [comment]
on controllers/pub.php try to locate the contact method, after form submission you would see there is an insertion of contact messages on the database insert the mail function you could use the native php mail function or try the built-in codeiginter mail class.   In your windows machine if you want to try mail you could use papercut app. please make the target email irm.support@irmevangelicalchurch.org

**Comment by slick2** [comment]
this is now fixed
