### ISSUE TITLE
Add Captcha

### ISSUE THREAD

**Issue by slick2** [irmec/irmec-website#9]
Add simple captcha to contact page so that we would not get unwanted spam.

**Comment by benjaminfaustino** [comment]
The captcha page will appear after the pressing submit button?

**Comment by slick2** [comment]
add a simple captcha on the form itself

**Comment by benjaminfaustino** [comment]
No function for captcha? Just captcha image?

**Comment by slick2** [comment]
a working captcha for contact page, an image plus validation

**Comment by benjaminfaustino** [comment]
Done.

**Comment by slick2** [comment]
this is done verified
